image:
  file: .gitpod.Dockerfile

tasks:
  - name: Run Web Server (8080)
    command: |
      bundle install
      bundle exec jekyll serve --host=0.0.0.0 --port=8080 --watch
    openMode: tab-after

ports:
- port: 8080
  onOpen: open-browser

vscode:
  extensions:
    - streetsidesoftware.code-spell-checker
    - james-yu.latex-workshop
    # - cweijan.vscode-office
